# Generated by Django 3.0.3 on 2020-06-01 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompliteShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_size_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')),
                ('product_size', models.CharField(max_length=20)),
                ('product_title', models.CharField(max_length=200)),
                ('product_prace', models.FloatField(verbose_name='цена товара')),
                ('product_quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
            ],
        ),
    ]
